### ISSUE TITLE
About the actions shapes issue without cuda

### ISSUE THREAD

**Issue by ziyan-wang98** [cvas-ug/bbrl-introspection#1]
Hi, I am trying to run programs and training without cuda. I found that the code cannot be run simply by setting cuda default to False (for example, Cuda is still used when setting the seed to somewhere). But when I try to change all cuda codes, an error will be reported in action clipe, as shown in the following figure:

Process SpawnProcess-1:
Traceback (most recent call last):
  File "/Users/ziyanwang/opt/anaconda3/envs/bbrl_py36/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/ziyanwang/opt/anaconda3/envs/bbrl_py36/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/ziyanwang/Desktop/UCL 2/FYP/Code/bbrl-introspection-master/bbrl/approach.py", line 173, in test
    obs, reward, done, info = env.step(action)
  File "/Users/ziyanwang/opt/anaconda3/envs/bbrl_py36/lib/python3.6/site-packages/gym/wrappers/time_limit.py", line 31, in step
    observation, reward, done, info = self.env.step(action)
  File "/Users/ziyanwang/opt/anaconda3/envs/bbrl_py36/lib/python3.6/site-packages/gym/envs/robotics/robot_env.py", line 58, in step
    action = np.clip(action, self.action_space.low, self.action_space.high)
  File "<__array_function__ internals>", line 6, in clip
  File "/Users/ziyanwang/opt/anaconda3/envs/bbrl_py36/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2097, in clip
    return _wrapfunc(a, 'clip', a_min, a_max, out=out, **kwargs)
  File "/Users/ziyanwang/opt/anaconda3/envs/bbrl_py36/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 55, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/Users/ziyanwang/opt/anaconda3/envs/bbrl_py36/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 44, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
  File "/Users/ziyanwang/opt/anaconda3/envs/bbrl_py36/lib/python3.6/site-packages/numpy/core/_methods.py", line 141, in _clip
    um.clip, a, min, max, out=out, casting=casting, **kwargs)
  File "/Users/ziyanwang/opt/anaconda3/envs/bbrl_py36/lib/python3.6/site-packages/numpy/core/_methods.py", line 94, in _clip_dep_invoke_with_casting
    return ufunc(*args, out=out, **kwargs)
**ValueError: operands could not be broadcast together with shapes (5,) (4,) (4,)**

**Comment by npitsillos** [comment]
Hello @ziyan-wang98 and thank you for the issue!  From what I gather given the error output, the problem you are facing is the case where the dimensionality of the action you pass to the env does not match the one the env is expecting.  The code in this repo uses 5 actions whereas the original robotics env uses only 4.  What we did here is that we have extended the action space to include a rotation element as well, hence the error.  To go about this step by step I would suggest the following:

1. On environment creation with `gym.make(...)` print the dimensionality of the action space using `env.action_space.shape`.
2. The code for the behaviours should create an action with 5 values [x, y, z, close/open, rotate].

At this point you should see the mismatch in the actions where the environment has 4 values in the action expected and the bbrl code uses 5.

To solve this problem you should go into [this ](https://github.com/openai/gym/blob/master/gym/envs/robotics/fetch_env.py) file in your gym package within your anaconda environment and change lines [71](https://github.com/openai/gym/blob/master/gym/envs/robotics/fetch_env.py#L71) and [76](https://github.com/openai/gym/blob/master/gym/envs/robotics/fetch_env.py#L76) to the following respectively:

- assert action.shape == (5,)
- rot_ctrl = [0., action[4], 0., -action[4]]

This should solve the problem you are having.

PS: in the constructor function in the file linked above you should also change the `n_actions=4` param to be 5.

Try these and let me know. Also, do not hesitate to post here if you run into further problems!

**Comment by ziyan-wang98** [comment]
Thank you very much for such a detailed answer and amazing speed! **And it works**! I will continue to explore your outstanding work right now.
ps: I am preparing an environment with Cuda. I saw in the article that you use sponsored titan gpu. Can you provide a specific model or vision? At the same time, have you tried cloud training operations (such as AWS), do you meet the training needs?

**Comment by npitsillos** [comment]
Yes but to be honest training was not done on that GPU but instead on a GeForce RTX 2080 Super.  No, I have not tried but I would assume that there should not be an issue with that or if there is a cost of training on the cloud then it might be quite small since compute time results in almost half an hour for each behaviour (might be more or less but it is around there).  Training on the cloud would also be quite simple I believe since the only difficult thing would be setting up the machine and the virtual env.  After that, training should continue smoothly!
